  // Dados de exemplo
export const projects = [
    {
      id: "1",
      name: "Redesign do Site",
      description: "Redesenhar o site da empresa com um visual moderno",
      progress: 75,
      members: 5,
      tasks: { total: 24, completed: 18 },
      favorite: true,
      status: "Em andamento",
      dueDate: "15 Out, 2023",
    },
    {
      id: "2",
      name: "Desenvolvimento de App Mobile",
      description: "Desenvolver um app mobile para iOS e Android",
      progress: 40,
      members: 8,
      tasks: { total: 36, completed: 14 },
      favorite: true,
      status: "Em andamento",
      dueDate: "1 Dez, 2023",
    },
    {
      id: "3",
      name: "Campanha de Marketing",
      description: "Planejar e executar campanha de marketing para o Q4",
      progress: 20,
      members: 4,
      tasks: { total: 18, completed: 4 },
      favorite: false,
      status: "Planejamento",
      dueDate: "10 Nov, 2023",
    },
    {
      id: "4",
      name: "Lançamento de Produto",
      description: "Preparar o lançamento da nova linha de produtos",
      progress: 10,
      members: 10,
      tasks: { total: 18, completed: 6 },
      status: "Planejamento",
      dueDate: "5 Jan, 2024",
    },
    {
      id: "5",
      name: "Portal do Cliente",
      description: "Construir um portal do cliente para gerenciamento de contas",
      progress: 60,
      members: 4,
      tasks: { total: 7, completed: 4 },
      status: "Em andamento",
      dueDate: "30 Out, 2023",
    },
    {
      id: "6",
      name: "Ferramentas Internas",
      description: "Desenvolver ferramentas internas para produtividade da equipe",
      progress: 90,
      members: 2,
      tasks: { total: 11, completed: 6 },
      status: "Revisão",
      dueDate: "10 Out, 2023",
    },
  ]